version: "3.8"

services:

  portfolio:
    build:
      context: ./portfolio
    container_name: portfolio-app
    ports:
      - "5000:5000"
    restart: unless-stopped

  java-app:
    build:
      context: ./apps/java-app
    container_name: java-app
    ports:
      - "8080:8080"
    restart: unless-stopped
