---
- name: Configure DevOps Server
  hosts: web
  become: yes

  tasks:

    - name: Update packages
      yum:
        name: "*"
        state: latest

    - name: Install Git
      yum:
        name: git
        state: present

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes
